services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data:/app/data
      - ./output:/app/output
    container_name: tower_jump_backend
